PLA6113 Exploring Urban Data with Machine Learning
<br>
Wednesday January 13th, 2020
<br>
Erik Strand

# Lab 01: Intro to Python for ML
# SECTION 1:


## 1. Check your Python version

In [1]:
import platform
print(platform.python_version())

3.7.6


## 2. Code, output, and markdown

In [2]:
10+2

12

10 + 2 = 12

In [4]:
x = 20
y = 40
print (x + y)

60


We just calculated 20 + 40 and got a result, 60.

## 3. Basic math

Python can handle basic math operations. Let’s have a try:

In [ ]:
print (1 + 1)
print (1 + 2 + 3)
print (3 * 7 * 2)
print (4 / 2)

Let's see how order affects how code is run:

In [ ]:
print (4 * 6 + 5)
print ((4 * 6) + 5)
print (4 * (6 + 5))

## 4. Variables

Assigning variables: 
<br>
when assignining variables you can use "=" to assign variables:

In [7]:
A = 100
B = 3
C = 15
a,b = 5,7
D = 'Hello world!'
d = 'Hi there!'

In [8]:
print (a)
print (b)
print (B)
print (D)
print (d)

5
7
3
Hello world!
Hi there!


Reassigning variables:

In [9]:
a = 20
print (a)

20


## 5. Data Types
Getting the Data Type
<br>
You can get the data type of any object by using the type() function:
### 5-1. String

In [10]:
x = "Columbia University GSAPP"
type(x)

str

### 5-2. Integer

In [11]:
x = 20
type(x)

int

In [12]:
x = '20'
type(x)

str

### 5-3. Float

In [13]:
x = 3.7
type(x)

float

### 5-4. List
A collection which is ordered and changeable. Allows duplicate members.

In [14]:
x = ["New York", "Boston", "Chicago", "Los Angeles"]
type(x)

list

In [15]:
print (x[0])
print (x[1:3])
print (x[-1])

New York
['Boston', 'Chicago']
Los Angeles


In [16]:
x[1] = "Seattle"
print (x)

['New York', 'Seattle', 'Chicago', 'Los Angeles']


In [17]:
x.append("Houston")
x

['New York', 'Seattle', 'Chicago', 'Los Angeles', 'Houston']

__Task. Create and assign variable of a list with five different five different countries.__
* Print the first and the last items.
* Replace the third item to your last name.
* Print the list.

In [18]:
countries = ["Morocco", "Spain", "Japan", "Cambodia", "Ghana"]
print(countries[0], countries[4])

countries[2] = "Strand"

print(countries)

Morocco Ghana
['Morocco', 'Spain', 'Strand', 'Cambodia', 'Ghana']


### 5-4. Tuple
A collection which is ordered and unchangeable. Allows duplicate members.

In [19]:
x = ("New York", "Boston", "Chicago", "Los Angeles")
type(x)

tuple

In [20]:
print (x[0])
print (x[1:3])
print (x[-1])

New York
('Boston', 'Chicago')
Los Angeles


In [21]:
x[1] = "Seattle"
print (x)

TypeError: 'tuple' object does not support item assignment

### 5-5. Dictionary
A collection which is unordered, changeable and indexed. In Python dictionaries are written with curly brackets, and they have keys and values.

In [22]:
x = {"City": "New York", "State": "NY", "Country": "US"}
type(x)

dict

In [23]:
x["City"]

'New York'

In [24]:
x.get("City")

'New York'

In [25]:
x["Country"] = "United States"
x

{'City': 'New York', 'State': 'NY', 'Country': 'United States'}

### 5-6. Boolean
In programming you often need to know if an expression is True or False. You can evaluate any expression in Python, and get one of two answers, True or False. When you compare two values, the expression is evaluated and Python returns the Boolean answer:

In [26]:
print (10>6)
print (3>9)

True
False


## 6. Range
The range() function returns a sequence of numbers, starting from 0 by default, and increments by 1 (by default), and ends at a specified number.
* Syntax: range(start, stop, step) 

In [27]:
x = list(range(5))
print (x)

[0, 1, 2, 3, 4]


In [28]:
x = list(range(3,6))
print (x)

[3, 4, 5]


In [29]:
x = list(range(3, 20, 2))
print (x)

[3, 5, 7, 9, 11, 13, 15, 17, 19]


__Task. Create a list with a sequence of numbers from 5 to 50, increment by 15, using range().__

In [30]:
x = list(range(5,51,15))
print (x)

[5, 20, 35, 50]


## 7. Calling Fuctions

In [31]:
myList = list(range(15))
myList

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]

In [32]:
print (min(myList))
print (max(myList))
print (sum(myList))
print (len(myList))

0
14
105
15


__Task. Create a list with a sequence of numbers from 3 to 31, increment by 4, using range() and print mean value of the items.__
* Create a list and assign variable.
* Assign variables using calling functions based on needs (e.g. min, max, sum, or len)
* Pring mean value of the items in the list using mathematical expression.

In [33]:
myList = range(3, 32, 4)
a = sum(myList)
b = len(myList)

print (a/b)

17.0


## 8. Writing Functions
A function is a block of code which only runs when it is called. You can pass data, known as parameters, into a function. A function can return data as a result.

In [34]:
def myFunction():
    print("Welcome to Exploring Urban Data with Machine Learning") 

In [35]:
myFunction()

Welcome to Exploring Urban Data with Machine Learning


In [36]:
def myFunction(x,y):
    return x*y

In [37]:
myFunction(3,7)

21

In [38]:
def myFunction(x,y):
    a = x+y
    b = x-y
    c = x*y
    d = x/y
    return [a,b,c,d]

myFunction(8,2)

[10, 6, 16, 4.0]

__Task. Write a function to return average value of items in a list.__

In [39]:
def myFunction(list1):
    return(sum(list1)/len(list1))

myFunction([1,3,5,6,10])

5.0

## 9. Control Statement

In [40]:
a = 33
b = 200

if b > a:
    print("b is greater than a")

b is greater than a


In [41]:
a = 33
b = 33
if b > a:
    print("b is greater than a")
elif a == b:
    print("a and b are equal")

a and b are equal


In [42]:
a = 200
b = 33
if b > a:
    print("b is greater than a")
elif a == b:
    print("a and b are equal")
else:
    print("a is greater than b")

a is greater than b


## 10. For loops
A for loop is used for iterating over a sequence (that is either a list, a tuple, a dictionary, a set, or a string). This is less like the for keyword in other programming languages, and works more like an iterator method as found in other object-orientated programming languages. With the for loop we can execute a set of statements, once for each item in a list, tuple, set etc.

In [43]:
for i in range(6):
    print (i)

0
1
2
3
4
5


In [44]:
for fruit in ['apple', 'banana', 'tomato', 'orange']:
    print ("I like", fruit)

I like apple
I like banana
I like tomato
I like orange


In [45]:
colors = ["red", "yellow", "pink"]
fruits = ["apple", "banana", "tomato", "orange"]

for x in colors:
    for y in fruits:
        print(x, y) 

red apple
red banana
red tomato
red orange
yellow apple
yellow banana
yellow tomato
yellow orange
pink apple
pink banana
pink tomato
pink orange


In [46]:
for i in range(5):
    if i == 3:
        print (0)
    else:
        print (i)

0
1
2
0
4


In [47]:
for i in range(5):
    if i == 3:
        pass
    else:
        print (i)

0
1
2
4


In [48]:
for i in range(5):
    if i == 3:
        break
    else:
        print (i)

0
1
2


# SECTION 2: Essential Libararies and Tools
* NumPy
* Pandas
* scikit-learn
* Very simple and basic machine learning example (pending)

## 1. NumPy
NumPy is one of the fundamental packages for scientific computing in the browser. 
* Multimensional arrays
* High-level mathematical functions such as linear algebra operations
* Important, because the NumPy array is the fundamental data structure in scikit-learn (which will be mainly used for machine learning algorithms)
* Data will have to be converted to a NumPy array
* Core functionality: ndarray class, multidimensinal (n-dimensional) array
* All elements in the array must be of the same data type (e.g. int, str, float...)

In [49]:
# Import the entire NumPy module
import numpy as np

### 1) Create a numpy array

In [50]:
x = np.array([[1,2,3],
              [4,5,6]])
print (x)

[[1 2 3]
 [4 5 6]]


### 2) Shape of matrix (array)

In [51]:
print (x.shape)

(2, 3)


### 3) Indexing

In [52]:
print (x[0])
print (x[1])
print (x[0][0])
print (x[1][2])

[1 2 3]
[4 5 6]
1
6


### 4) Keep in mind that, unlike Python lists, NumPy arrays have a fixed type. 
This means, for example, that if you attempt to insert a floating-point value to an integer array, the value will be silently truncated. 

In [53]:
x[0][1] = 5.7864
print (x)

[[1 5 3]
 [4 5 6]]


### 5) Accessing array rows and columns.    
One commonly needed routine is accessing single rows or columns of an array. You can do this by combining indexing and slicing, using an empty slice marked by a single colon (:):

In [54]:
print (x[:, 0])
print (x[:, 2])

[1 4]
[3 6]


### 6) NumPy's arithmetic operators

In [55]:
x = np.array([1,2,3,4,5,6])
print (x)

[1 2 3 4 5 6]


In [56]:
print (x+3)
print (x-10)
print (x*3)

[4 5 6 7 8 9]
[-9 -8 -7 -6 -5 -4]
[ 3  6  9 12 15 18]


In [57]:
x = np.array([-10,5,-6,6,5,10])
print ("Original array: ",x)
print ("Absolute values: ", np.abs(x))
print ("Natural logarithm values: ", np.log(x))
print ("Base-10 logarithm values: ", np.log10(x))
print ("Exponential values: ", np.exp(x))
print ("Exponential values: ", np.round(np.exp(x),2))

Original array:  [-10   5  -6   6   5  10]
Absolute values:  [10  5  6  6  5 10]
Natural logarithm values:  [       nan 1.60943791        nan 1.79175947 1.60943791 2.30258509]
Base-10 logarithm values:  [       nan 0.69897           nan 0.77815125 0.69897    1.        ]
Exponential values:  [4.53999298e-05 1.48413159e+02 2.47875218e-03 4.03428793e+02
 1.48413159e+02 2.20264658e+04]
Exponential values:  [    0.     148.41     0.     403.43   148.41 22026.47]


/Users/erik_strand/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: RuntimeWarning: invalid value encountered in log
  after removing the cwd from sys.path.
/Users/erik_strand/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: RuntimeWarning: invalid value encountered in log10
  """


### 7) Calling built-in functions

In [58]:
x = np.array([[1,2,3,4,5],
             [2,3,4,5,6],
             [3,4,5,6,7]])
print (x)

[[1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]]


In [59]:
print (x.sum())
print (x.min())
print (x.argmin())
print (x.max())
print (x.argmax())
print (x.mean())
print (x.std())

60
1
0
7
14
4.0
1.632993161855452


In [60]:
print (np.median(x))
print (np.sum(x))
print (np.min(x))
print (np.argmin(x))
print (np.mean(x))
print (np.std(x))

4.0
60
1
0
4.0
1.632993161855452


## 2. Pandas
Pandas is a Python library for data wrangling and analysis.
* Data structure called the DataFrame - modeled after the R DataFrame
* Simply, it is like a table, similar to an Excel spreadsheet
* Great range of methods to modify and operate on data tables
* SQL-like queries, joins of tables
* In contrast to NumPy, Pandas allows each column to have a separate data type (e.g. one for string, one for float, one for datetime etc.)
* Ingest from a variety of data file formats and data bases (SQL, Excel file, csv, json)

In [61]:
# Import the entire pandas module
import pandas as pd

### 1) Excel

In [63]:
df = pd.read_excel('../data/311_Service_Requests_01062020_sample.xlsx')

### 2) comma-separated values (CSV)
* We will mostly use this format

In [65]:
df = pd.read_csv('../data/311_Service_Requests_01062020.csv')

In [66]:
df.head(2)

Unique Key            Created Date             Closed Date Agency  \
0    45321376  01/06/2020 12:00:00 AM  01/22/2020 12:00:01 AM  DOHMH   
1    45322953  01/06/2020 12:00:00 AM  01/21/2020 12:00:01 AM  DOHMH   

                               Agency Name  Complaint Type Descriptor  \
0  Department of Health and Mental Hygiene  Food Poisoning     1 or 2   
1  Department of Health and Mental Hygiene  Food Poisoning  3 or More   

                Location Type  Incident Zip        Incident Address  ...  \
0         1-2 Family Dwelling       10467.0  3311 WHITE PLAINS ROAD  ...   
1  Restaurant/Bar/Deli/Bakery       11375.0        64-18 108 STREET  ...   

  Vehicle Type Taxi Company Borough Taxi Pick Up Location Bridge Highway Name  \
0          NaN                  NaN                   NaN                 NaN   
1          NaN                  NaN                   NaN                 NaN   

  Bridge Highway Direction Road Ramp Bridge Highway Segment   Latitude  \
0                      NaN       NaN                    NaN  40.873639   
1                      NaN       NaN                    NaN  40.732517   

   Longitude                                 Location  
0 -73.867095   (40.8736393816693, -73.86709503705343)  
1 -73.849397  (40.73251661488513, -73.84939676972941)  

[2 rows x 41 columns]

### 3) JSON file

* JSON stands for JavaScript Object Notation
* JSON is a lightweight format for storing and transporting data
* JSON is often used when data is sent from a server to a web page
* JSON is "self-describing" and easy to understand

__Example of JSON data__: an array of 3 employee records
![image.png](attachment:image.png)

__Exmaple of JSON data__: NYC311 data <br>
https://data.cityofnewyork.us/resource/erm2-nwe9.json

* JSON is good for using API based data acquisition with SQL-like query

In [67]:
# Load libraries for the use of JSON and url
import urllib.request, json 

In [68]:
# Simply load top 1000 rows from url based JSON file
df = pd.read_json("https://data.cityofnewyork.us/resource/erm2-nwe9.json") 

In [69]:
df.head(2)

unique_key             created_date agency                   agency_name  \
0    49562095  2021-01-19T01:19:49.000    DOT  Department of Transportation   
1    49562719  2021-01-19T00:56:00.000    DOT  Department of Transportation   

           complaint_type        descriptor  incident_zip incident_address  \
0        Street Condition           Pothole       11372.0        83 STREET   
1  Street Light Condition  Street Light Out       11233.0              NaN   

  street_name         cross_street_1  ... :@computed_region_sbqj_enih  \
0   83 STREET  RICHARD CECERE CORNER  ...                        73.0   
1         NaN                    NaN  ...                        46.0   

  intersection_street_1 intersection_street_2 facility_type bbl closed_date  \
0                   NaN                   NaN           NaN NaN         NaN   
1              BROADWAY         CONWAY STREET           NaN NaN         NaN   

  location_type landmark  vehicle_type  taxi_pick_up_location  
0           NaN      NaN           NaN                    NaN  
1           NaN      NaN           NaN                    NaN  

[2 rows x 40 columns]

### 4) Dataframe basic

In [71]:
df = pd.read_csv('../data/311_Service_Requests_01062020.csv')

In [72]:
# print column names
print (df.columns.tolist())

['Unique Key', 'Created Date', 'Closed Date', 'Agency', 'Agency Name', 'Complaint Type', 'Descriptor', 'Location Type', 'Incident Zip', 'Incident Address', 'Street Name', 'Cross Street 1', 'Cross Street 2', 'Intersection Street 1', 'Intersection Street 2', 'Address Type', 'City', 'Landmark', 'Facility Type', 'Status', 'Due Date', 'Resolution Description', 'Resolution Action Updated Date', 'Community Board', 'BBL', 'Borough', 'X Coordinate (State Plane)', 'Y Coordinate (State Plane)', 'Open Data Channel Type', 'Park Facility Name', 'Park Borough', 'Vehicle Type', 'Taxi Company Borough', 'Taxi Pick Up Location', 'Bridge Highway Name', 'Bridge Highway Direction', 'Road Ramp', 'Bridge Highway Segment', 'Latitude', 'Longitude', 'Location']


In [73]:
# print total number of rows
print (len(df))

6037


In [74]:
# check data types
print (df.dtypes)

Unique Key                          int64
Created Date                       object
Closed Date                        object
Agency                             object
Agency Name                        object
Complaint Type                     object
Descriptor                         object
Location Type                      object
Incident Zip                      float64
Incident Address                   object
Street Name                        object
Cross Street 1                     object
Cross Street 2                     object
Intersection Street 1              object
Intersection Street 2              object
Address Type                       object
City                               object
Landmark                           object
Facility Type                      object
Status                             object
Due Date                           object
Resolution Description             object
Resolution Action Updated Date     object
Community Board                   

In [75]:
# print data header with certain columns
df[['Unique Key', 'Agency Name', 'Complaint Type', 'Incident Zip', 'Borough', 'Created Date']].head()

Unique Key                              Agency Name  Complaint Type  \
0    45321376  Department of Health and Mental Hygiene  Food Poisoning   
1    45322953  Department of Health and Mental Hygiene  Food Poisoning   
2    45319607  Department of Health and Mental Hygiene  Food Poisoning   
3    45319110  Department of Health and Mental Hygiene  Food Poisoning   
4    45319119  Department of Health and Mental Hygiene  Food Poisoning   

   Incident Zip    Borough            Created Date  
0       10467.0      BRONX  01/06/2020 12:00:00 AM  
1       11375.0     QUEENS  01/06/2020 12:00:00 AM  
2       10128.0  MANHATTAN  01/06/2020 12:00:00 AM  
3       10039.0  MANHATTAN  01/06/2020 12:00:00 AM  
4       10467.0      BRONX  01/06/2020 12:00:00 AM

### 5) Downsize data with certain columns
Let's keep 6 columns used above ('Unique Key', 'Agency Name', 'Complaint Type', 'Incident Zip', 'Borough', and 'Created Date')

In [76]:
df2 = df[['Unique Key', 'Agency Name', 'Complaint Type', 'Incident Zip', 'Borough', 'Created Date']]
df2.head(2)

Unique Key                              Agency Name  Complaint Type  \
0    45321376  Department of Health and Mental Hygiene  Food Poisoning   
1    45322953  Department of Health and Mental Hygiene  Food Poisoning   

   Incident Zip Borough            Created Date  
0       10467.0   BRONX  01/06/2020 12:00:00 AM  
1       11375.0  QUEENS  01/06/2020 12:00:00 AM

### 6) Print data by index
Let's keep 6 columns used above ('Unique Key', 'Agency Name', 'Complaint Type', 'Incident Zip', 'Borough', and 'Created Date')

In [77]:
df2.iloc[500:505]

Unique Key                                        Agency Name  \
500    45323527             Department of Environmental Protection   
501    45319486                    New York City Police Department   
502    45323281  Department of Housing Preservation and Develop...   
503    45320184                    New York City Police Department   
504    45319827                               BCC - Brooklyn South   

                        Complaint Type  Incident Zip   Borough  \
500                        Air Quality       11249.0  BROOKLYN   
501                    Illegal Parking       11377.0    QUEENS   
502                     HEAT/HOT WATER       10474.0     BRONX   
503                   Blocked Driveway       11208.0  BROOKLYN   
504  Missed Collection (All Materials)       11218.0  BROOKLYN   

               Created Date  
500  01/06/2020 06:47:00 AM  
501  01/06/2020 06:47:00 AM  
502  01/06/2020 06:47:34 AM  
503  01/06/2020 06:48:30 AM  
504  01/06/2020 06:49:00 AM

### 7) Rename columns
Let's rename columne 'Incident Zip' to 'Zipcode'

In [78]:
df2.rename(columns = {'Incident Zip':'Zipcode'}, inplace = True) 
df2.head(2)

/Users/erik_strand/opt/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py:4304: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,


Unique Key                              Agency Name  Complaint Type  \
0    45321376  Department of Health and Mental Hygiene  Food Poisoning   
1    45322953  Department of Health and Mental Hygiene  Food Poisoning   

   Zipcode Borough            Created Date  
0  10467.0   BRONX  01/06/2020 12:00:00 AM  
1  11375.0  QUEENS  01/06/2020 12:00:00 AM

### 8) Sort values

In [90]:
df2['Zipcode'] = df2['Zipcode'].astype('Int64')
df2.sort_values(by='Zipcode', ascending=True).head()

/Users/erik_strand/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


Unique Key                      Agency Name  \
5596    45322923  New York City Police Department   
2524    45320638  New York City Police Department   
3096    45324354  New York City Police Department   
4899    45319028          Department of Buildings   
1310    45327337         Department of Sanitation   

                     Complaint Type  Zipcode    Borough  \
5596            Noise - Residential    10001  MANHATTAN   
2524                Illegal Parking    10001  MANHATTAN   
3096            Noise - Residential    10001  MANHATTAN   
4899  General Construction/Plumbing    10001  MANHATTAN   
1310                       Graffiti    10001  MANHATTAN   

                Created Date  
5596  01/06/2020 10:19:50 PM  
2524  01/06/2020 12:16:41 PM  
3096  01/06/2020 01:42:59 PM  
4899  01/06/2020 07:23:01 PM  
1310  01/06/2020 09:44:00 AM

### 9) Print rows based on values

    Print rows where "Zipcode" is 10011 and "Complaint Type" is 'Illegal Parking'


In [92]:
df2[(df2['Zipcode']==10011) & (df2['Complaint Type']=='Illegal Parking')]

Unique Key                      Agency Name   Complaint Type  Zipcode  \
4993    45325003  New York City Police Department  Illegal Parking    10011   
5959    45322573  New York City Police Department  Illegal Parking    10011   
5975    45320348  New York City Police Department  Illegal Parking    10011   

        Borough            Created Date  
4993  MANHATTAN  01/06/2020 07:48:07 PM  
5959  MANHATTAN  01/06/2020 11:41:21 PM  
5975  MANHATTAN  01/06/2020 11:44:16 PM

### 10) Create new column

    Create column name 'count' with value 1 (integer)


In [93]:
df2['count'] = 1
df2.head(2)

/Users/erik_strand/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


Unique Key                              Agency Name  Complaint Type  \
0    45321376  Department of Health and Mental Hygiene  Food Poisoning   
1    45322953  Department of Health and Mental Hygiene  Food Poisoning   

   Zipcode Borough            Created Date  count  
0    10467   BRONX  01/06/2020 12:00:00 AM      1  
1    11375  QUEENS  01/06/2020 12:00:00 AM      1

### 11) Groupby

    A groupby operation involves some combination of splitting the object, applying a function, and combining the results. This can be used to group large amounts of data and compute operations on these groups.
    Let's groupby Borough to calculate how many 311 complaints were reported


In [94]:
result = df2[['Borough', 'count']].groupby('Borough').count()
result

count
Borough             
BRONX           1069
BROOKLYN        1763
MANHATTAN       1417
QUEENS          1485
STATEN ISLAND    261
Unspecified       42

### 12) Export your dataframe 

    Syntax: YOUR_DATAFRAME_NAME.to_csv('FILE_PATH')

In [95]:
result.to_csv('../output/result_example.csv')

# Assignment 01
### In this assignment we will be starting to work with Python. Please submit a python script and markdown using Jupyter notebook (.ipynb file) with your submission. File name should be "Lastname_Firstname_assignment01.ipynb" and submit to Canvas. Also provide step-by-step code for credit and do not forget to run your code before submitting.

* Don’t forget to finish the lab started in the last leb session. 
* Please do not share works publicly on GitHub or other places until after the deadline.
* Some part of coding can be identical if you work in the same group but annotation/comment must be individual.


## 1. Finish setting up your Jupyter notebook and folders for this semester.
This is very trivial task but it will be really important to develop reproducible work pipilines. Please insert a screenshot of the "EUDML" folder of Jupyter notebook. There should be at least 4 different folders - data, script, output, and image. To embed image in markdwon cells, you can do ctrl+v your screenshot.

<img src="../image/folder.png" width="800" height="400">

*Markdown*

LaTeX: $\alpha$$^2$

## 2. Create a function to calculate and categorize BMI index.
Body Mass Index (BMI) is a measure of body fat that applies to adult men and women. BMI is calculated by using weight and height information, and the calculated index is categorized as four different groups as follows.

$BMI = \frac{weight(kg)}{{height(m)}^{2}}$

BMI Categories:
* Underweight = <18.5
* Normal weight = 18.5–24.9
* Overweight = 25–29.9
* Obesity = BMI of 30 or greater 

Please create a function called BMIFunc in three arguments, weight, height, and gender to calculate the BMI of a given person and print one of BMI categories based on the above four groups. Please wirte a script to return the following example output if you take BMIFunc(60, 170, Female) as an input:

----- BMI Calculator -----
<br>
Gender: Female
<br>
Weigth: 60 (kg)
<br>
Height: 170 (cm)
<br>
BMI: 20.8
<br>
Category: Normal weight


In [104]:
def BMIFunc(weight, height, gender):
    height_m = height / 100 # change height from cm to m
    bmi = round(weight / (height_m*height_m), 1) # calculates BMI
    if(bmi >= 30): # categorizes BMI based on thresholds
        cat = "Obese"
    elif(bmi >= 25): 
        cat = "Overweight"
    elif(bmi >= 18.5): 
        cat = "Normal Weight"
    else:
        cat = "Underweight"
    print("----- BMI Calculator -----\nGender:", gender, 
          "\nWeight:", weight, 
          "(kg)\nHeight:", height, 
          "(cm)\nBMI:", bmi, 
          "\nCategory:", cat)

BMIFunc(60, 170, "Female")

----- BMI Calculator -----
Gender: Female 
Weight: 60 (kg)
Height: 170 (cm)
BMI: 20.8 
Category: Normal Weight


## 3. Create a function with for loops taking an integer (n) as an input to print the following output.
[1]
<br>
[1]
<br>
[1,3]
<br>
[1,3,]
<br>
...
<br>
[1,3,5...n-2] (line number n-1) if n is odd OR [1,3,5...n-1] (line number n-1) if n is even
<br>
* If you take 7 for input, then you will have 
<br>
[1]
<br>
[1]
<br>
[1,3]
<br>
[1,3]
<br>
[1,3,5]
<br>
[1,3,5]
<br>
* If input is 6, then the output will be
<br>
[1]
<br>
[1]
<br>
[1,3]
<br>
[1,3]
<br>
[1,3,5]

Write a function below and test with input 50.

In [115]:
def sequence(n): 
    for i in range(n - 1): 
        print(list(range(1, i + 2, 2)))
        
sequence(6)

[1]
[1]
[1, 3]
[1, 3]
[1, 3, 5]


## 4. Create a function to get all available origin-destination combinations.
Let's assume there are 6 cities in the U.S., New York, Boston, Los Angeles, Seattle, Chicago, and San Francisco. Create a function called flightRoutes to print all available airline routes from origin cities to destination cities. There are few conditions to consider:
* The airport in Chicago is closed due to heavy snow, meaning flights cannot depart or arrive.
* Boston to Los Angeles is not available temporarily.
* Seattle to New York is not available temporarily.
* Use pass AND/OR break AND/OR countinue command.

<br>
Write your code below and provide your output. Ideal output would be similar to the followings:
<br>
Origin: New York - Destination: Boston
<br>
Origin: New York - Destination: Los Angeles
<br>
...

In [117]:
def flightRoutes(): 
    cities = ["New York", "Boston", "Los Angeles", "Seattle", "Chicago", "San Francisco"]
    for i in cities: 
        for j in cities: 
            if i == j: 
                pass
            elif i == "Chicago" or j == "Chicago": 
                pass
            elif i == "Boston" and j == "Los Angeles": 
                pass
            elif i == "Seattle" and j == "New York":
                pass
            else: 
                print("Origin:", i, "- Destination:", j)
    
flightRoutes()

Origin: New York - Destination: Boston
Origin: New York - Destination: Los Angeles
Origin: New York - Destination: Seattle
Origin: New York - Destination: San Francisco
Origin: Boston - Destination: New York
Origin: Boston - Destination: Seattle
Origin: Boston - Destination: San Francisco
Origin: Los Angeles - Destination: New York
Origin: Los Angeles - Destination: Boston
Origin: Los Angeles - Destination: Seattle
Origin: Los Angeles - Destination: San Francisco
Origin: Seattle - Destination: Boston
Origin: Seattle - Destination: Los Angeles
Origin: Seattle - Destination: San Francisco
Origin: San Francisco - Destination: New York
Origin: San Francisco - Destination: Boston
Origin: San Francisco - Destination: Los Angeles
Origin: San Francisco - Destination: Seattle


## 5. Write a code to return a list of prime numbers. 
A prime number is a positive integer which has no other factors except 1 and the number itself. For example 2, 3, 5, 7, 11, etc. are prime numbers, but 8 is not because 8 has four factors; 1, 2, 4, 8.

Please write a function to take a positive integer as an input to return a list of prime numbers less than the input integer. For example, if you take 10 as an input, then your code will return [2,3,5,7]. 

Write your code below and print your output of taking input integer 100.

Hint: please google and use Python operators %.

In [134]:
def primeNumbers(n):
    primes = []
    for i in range(2, n + 1): # check each number between 2 and n for prime/not prime (0 and 1 always not prime)
        is_prime = True
        for j in range(2, i, 1): 
            if i % j == 0: 
                is_prime = False
        if is_prime: 
            primes.append(i)
    if len(primes) == 0: 
        print("No prime numbers")
    else:
        print(primes)

primeNumbers(100)

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97]
